version: "3.8"
services:
  dashy:
    # To build from source, replace 'image: lissy93/dashy' with 'build: .'
    # build: .
    image: lissy93/dashy
    container_name: Dashboard
    # Pass in your config file below, by specifying the path on your host machine
    volumes:
      - </path/to/your>/dashy/public/conf.yml:/app/public/conf.yml
      - </path/to/your>/dashy/icons:/app/public/item-icons/icons 
    ports:
      - 8295:80
    # Set any environmental variables
    environment:
      - NODE_ENV=production
    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
    #  - UID=1000
    #  - GID=1000
    # Specify restart policy
    restart: unless-stopped